development:
  adapter: postgresql
  encoding: unicode
  database: personalblog_doz7
  pool: 5

 
production:
  adapter: postgresql
  encoding: unicode
  database: personalblog_doz7
  url: <%= ENV['POSTGRES_URL'] %>

